name: Main

on:
  push:
    branches:
      - 'main'
jobs:
  test:
    uses: './.github/workflows/test.yml'
  update-readme:
    permissions:
      contents: write
    needs: test
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@v4'

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: 'Install dependencies'
        run: pnpm install

      - name: 'Check if CodebaseKB API key is set'
        run: |
          if [ -z "${{ secrets.CODEBASE_KB_API_KEY }}" ]; then
            echo "Required secret CODEBASE_KB_API_KEY is not set."
            exit 1
          else
            echo "Secret CODEBASE_KB_API_KEY is set. Proceeding with workflow."
          fi

      - name: 'Check if CodebaseKB API key is set'
        run: |
          if [ -z "${{ secrets.BASE_API_URL }}" ]; then
            echo "Required secret BASE_API_URL is not set."
            exit 1
          else
            echo "Secret CODEBASE_KB_API_KEY is set. Proceeding with workflow."
          fi

      - name: 'Build'
        run: pnpm build
        
      - name: 'Rebuild README.md'
        run: 'node dist/scripts/buildReadme.js'

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Display .markdownlint.json
        run: cat .markdownlint.json
  
      - name: Check if commit was made by GitHub Actions
        id: check_commit
        run: |
          if git log -1 --pretty=%B | grep -q 'Automated commit by GitHub Actions:'; then
            echo "Commit was made by GitHub Actions, exiting..."
            exit 0
          fi

      - name: Commit changes
        run: |
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated commit by GitHub Actions: Rebuild README"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main

      - name: 'Upload markdown metadata to db'
        env: 
          CODEBASE_KB_API_KEY: ${{ secrets.CODEBASE_KB_API_KEY }}
          BASE_API_URL: ${{ secrets.BASE_API_URL }}
        run: node dist/scripts/getSnippet.js

      - name: 'Check and sync deleted files to db'
        env: 
          CODEBASE_KB_API_KEY: ${{ secrets.CODEBASE_KB_API_KEY }}
          BASE_API_URL: ${{ secrets.BASE_API_URL }}
        run: node dist/scripts/syncDeletedFiles.js
